const mongoose = require("mongoose");

// Persists the operator override for required manpower per *line* (machine) per shift.
// `lineId` is a deterministic id generated by the frontend from schedule data.
const manpowerLineSettingsSchema = new mongoose.Schema(
  {
    lineId: {
      type: String,
      required: true,
      unique: true,
      index: true,
      trim: true,
    },
    quota: {
      type: Number,
      required: true,
      min: 0,
      max: 99_999,
    },
  },
  { timestamps: true }
);

module.exports = mongoose.model(
  "ManpowerLineSettings",
  manpowerLineSettingsSchema,
  "manpower_line_settings"
);

